### ISSUE TITLE
Ability to have the timestamp show seconds elapsed?

### ISSUE THREAD

**Issue by ColdDev** [Pigpog/discord-rich-presence-cli#2]
Hi there, I love this project, however one problem I have with it is that I am unable to make it show time elapsed, rather than time left. Is this something that could be introduced as an option on launch or something?

**Comment by Pigpog** [comment]
I'm glad you like it, I think it's pretty nifty myself, though it could probably be better. I have just added startTimestamp in this commit 5957dca651a5848bab1fbf1e9afa023d71477372. If you want it to display time elapsed, you have to give a startTimestamp (current UNIX time) and specify 0 for endTimestamp.

Thanks for the suggestion and also your interest in my program!

**Comment by ColdDev** [comment]
Thank you for adding this so quickly haha! I thought this was one of those projects where its owners/maintainers only checked GitHub once in a blue moon. I'll be sure to use this way more often now :D

**Comment by Pigpog** [comment]
I love fulfilling feature requests quickly, wish I had got a notification about this issue so I could have done it immediately!
